export {ReactComponent as AboutSvg} from "./about.svg";
export {ReactComponent as KnowHowsSvg} from "./knowhows.svg";
export {ReactComponent as RecipesSvg} from "./recipes.svg";
export {ReactComponent as HomeSvg} from "./home.svg";
export {ReactComponent as Logo} from "./logo.svg";
export {ReactComponent as Soups} from "./soups.svg";
export {ReactComponent as ThemeToggler} from "./theme-toggler.svg";
export {ReactComponent as ContactSvg} from "./contact.svg";
export {ReactComponent as Hamburger} from "./hamburger.svg"